### ISSUE TITLE
No module named 'redis.commands'

### ISSUE THREAD

**Issue by diman82** [cunla/fakeredis-py#121]
**Describe the bug**
Using latest version of the package 2.7.1, I get the following error:

`ERROR: tests.test_custom_xcom (nose2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_custom_xcom
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nose2/plugins/loader/discovery.py", line 204, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nose2/util.py", line 76, in module_from_name
    __import__(name)
  File "/home/runner/work/data-management-airflow-2/data-management-airflow-2/tests/test_custom_xcom.py", line 7, in <module>
    import fakeredis
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/fakeredis/__init__.py", line 1, in <module>
    from ._server import FakeServer, FakeRedis, FakeStrictRedis, FakeConnection, FakeRedisConnSingleton
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/fakeredis/_server.py", line 12, in <module>
    from fakeredis._fakesocket import FakeSocket
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/fakeredis/_fakesocket.py", line 1, in <module>
    from fakeredis.stack import JSONCommandsMixin
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/fakeredis/stack/__init__.py", line 7, in <module>
    raise e
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/fakeredis/stack/__init__.py", line 3, in <module>
    from redis.commands.json.path import Path  # noqa: F401
ModuleNotFoundError: No module named 'redis.commands'`

**To Reproduce**
1. import fakeredis module

**Expected behavior**
sub-dependency module is correctly imported

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu)
 - python version: 3.8.10
 - redis-py version: 2.7.1

**Additional context**
having latest apache-airflow-providers-redis package, which installs redis==3.5.3

**Comment by cunla** [comment]
Are you using json module?

**Comment by cunla** [comment]
Hi, In version 2.0.0 support for redis-py < 4 was removed.

However, you are using redis-py version: 2.7.1 while [the apache-airflow-providers-redis  package requires redis-py ~3.2](https://github.com/apache/airflow/blob/main/airflow/providers/redis/provider.yaml#L41).

I can update fakeredis so you won't get this exception, but you won't be able to use JSON commands.

**Comment by diman82** [comment]
@cunla Yes, please update fakeredis library, IMHO the best would convert this exception to warning

**Comment by cunla** [comment]
Fixed, will be in next version

**Comment by diman82** [comment]
@cunla When approximately should we expect the new version?

**Comment by hyeongguen-song** [comment]
@diman82 , cunla just released a new version

**Comment by diman82** [comment]
@cunla @hyeongguen-song  Confriming issue has been resolved
