### ISSUE TITLE
ModuleNotFoundError: No module named 'async_timeout'

### ISSUE THREAD

**Issue by peterschutt** [cunla/fakeredis-py#130]
Hi!

Thanks for all of your efforts maintaining this library.

`redis-py` no longer installs `async_timeout` on python 3.11 (https://github.com/redis/redis-py/pull/2602/files), which manifests in this error in our CI:

```
ImportError while loading conftest '/home/runner/work/starlite/starlite/tests/conftest.py'.
tests/conftest.py:54: in <module>
    from fakeredis.aioredis import FakeRedis
.venv/lib/python3.11/site-packages/fakeredis/aioredis.py:12: in <module>
    import async_timeout
E   ModuleNotFoundError: No module named 'async_timeout'
```

Reproduction:

```
peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ pyenv shell 3.11.2
peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ python -m venv .venv
peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ . .venv/bin/activate
(.venv) peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ python --version
Python 3.11.2
(.venv) peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ python -m pip install fakeredis
Collecting fakeredis
  Using cached fakeredis-2.10.1-py3-none-any.whl (57 kB)
Collecting redis<5,>=4
  Downloading redis-4.5.2-py3-none-any.whl (238 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.5/238.5 kB 5.4 MB/s eta 0:00:00
Collecting sortedcontainers<3.0,>=2.4
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, redis, fakeredis
Successfully installed fakeredis-2.10.1 redis-4.5.2 sortedcontainers-2.4.0

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
(.venv) peter@peter-Inspiron-15-5510:~/PycharmProjects/starlite$ python -c "from fakeredis.aioredis import FakeRedis"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/peter/PycharmProjects/starlite/.venv/lib/python3.11/site-packages/fakeredis/aioredis.py", line 12, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'
```

As `fakeredis-py` directly depends on `async_timeout` perhaps you can consider adding it to the lib's dependencies. Alternatively, you could go all-in on the transitive dependency and import it from `redis-py`, e.g., `from redis.asyncio.connection import async_timeout`, and leverage their version specific aliasing.

**Comment by cunla** [comment]
I noticed it already on the actions. As a short term solution it can be added, but I would like to see how redis-py how avoid this dependency and perhaps it can be avoided altogether here as well

**Comment by peterschutt** [comment]
They are using `asyncio.timeout` in 3.11, and still depend on `async_timeout` for 3.10 and lower.

For now I will add `async_timeout` to our dev deps.

**Comment by stinovlas** [comment]
I confirm this is now fixed at `master` :+1:.
