### ISSUE TITLE
xinfo_stream returns data for a stream that doesn't exist

### ISSUE THREAD

**Issue by steve-mavens** [cunla/fakeredis-py#296]
**Describe the bug**

This is a difference between fakeredis and real redis. On real redis if you call xinfo_stream for a stream name that doesn't exist, you get an exception. On fakeredis you get back dummy data.

**To Reproduce**

```
import fakeredis
import redis


def main() -> None:
    fake = fakeredis.FakeRedis(version=6)
    assert fake.keys("*exist*") == []
    print('fakeredis returns', fake.xinfo_stream("nonexistent"))
    assert fake.keys("*exist*") == []

    real = redis.Redis("localhost")
    assert real.keys("*exist*") == []
    print('real redis returns', real.xinfo_stream("nonexistent"))


if __name__ == "__main__":
    main()
```

Result is:

```
fakeredis returns {'length': 0, 'groups': 0, 'first-entry': None, 'last-entry': None, 'max-deleted-entry-id': b'0-0', 'entries-added': 0, 'recorded-first-entry-id': b'0-0'}
Traceback (most recent call last):
  File "fakeredis_xinfo_test.py", line 17, in <module>
    main()
  File "fakeredis_xinfo_test.py", line 13, in main
    print('real redis returns', real.xinfo_stream("nonexistent"))
  <snip the rest of the stack trace>
redis.exceptions.ResponseError: no such key
```

**Expected behavior**

fakeredis raises exception to match real redis's behaviour

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - python version 3.8.16
 - redis-py version 5.0.2
 - full requirements.txt? I haven't created a minimal environment to reproduce the problem, but fakeredis version is 2.21.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/fakeredis-py/issues/296">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/fakeredis-py/issues/296/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/fakeredis-py/issues/296/pledge.svg">
</picture>
</a>

**Comment by steve-mavens** [comment]
My actual code uses fakeredis.aioredis.FakeRedis and has the same issue, but I wrote the minimal demonstration code using the synchronous client to see whether async was anything to do with it. Doesn't seem to be!
